live_config_reload = true

import = ["~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"]

[shell]
program = "/bin/zsh"

[env]
TERM = "xterm-256color"

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off"}

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.8
blur = true
startup_mode = "Maximized"

[font]
size = 15.0
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
bold = { family = "JetBrainsMono Nerd Font", style = "Heavy" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Heavy Italic" }
italic = { family = "JetBrainsMono Nerd Font", style = "Medium Italic" }
